## makeCacheMatrix and cacheSolve collaboratively cache a matrix, 
## calculate its inverse and cache its inverse. Calculation
## of the inverse is only performed in case the inverse of 
## the matrix has not been calculated previously; if the 
## inverse has been cached previously, chached data are retrieved


## makeCacheMatrix generates a list of functions to cache a matrix 
## (supplied as argument) and its inverse

makeCacheMatrix <- function(x = matrix()) {
  i <- NULL
  get <- function() x
  setinv <- function(inverse) i <<- inverse
  getinv <- function() i
  list(get = get, setinv = setinv, getinv = getinv)
}


## cacheSolve checks whether a list generated by makeCacheMatrix 
## has a cached calculated inverse. If so, the cached inverse is
## displayed, if not, the inverse is calculated

cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  i <- x$getinv()
  if(!is.null(i)) {
    message("getting cached data")
    return(i)
  }
  data <- x$get()
  i <- solve(data, ...)
  x$setinv(i)
  i
}
